




SELECT F.CD_DEPARTAMENTO,
       COUNT(F.NM_FUNCIONARIO) AS NUMERO
       INTO #TEMP
       FROM FUNCIONARIOS AS F
       GROUP BY F.CD_DEPARTAMENTO



SELECT * FROM #TEMP

USE FUNCIONARIOS
SELECT D.NM_DEPARTAMENTO, COUNT(*) AS [TOTAL_FUNCIONARIOS]
INTO #tabela FROM DEPARTAMENTOS D JOIN FUNCIONARIOS F ON
D.CD_DEPARTAMENTO = F.CD_DEPARTAMENTO
GROUP BY D.NM_DEPARTAMENTO

SELECT F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO, F.CD_BANCO FROM FUNCIONARIOS AS F
WHERE F.CD_DEPARTAMENTO IN (3, 4)
UNION
SELECT F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO, F.CD_BANCO FROM FUNCIONARIOS AS F
WHERE F.CD_BANCO IS NULL

SELECT F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO, F.CD_BANCO FROM FUNCIONARIOS AS F
WHERE F.CD_DEPARTAMENTO IN (3, 4)
INTERSECT
SELECT F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO, F.CD_BANCO FROM FUNCIONARIOS AS F
WHERE F.CD_BANCO IS NULL


SELECT F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO, F.CD_BANCO FROM FUNCIONARIOS AS F
WHERE F.CD_DEPARTAMENTO IN (3, 4)
EXCEPT
SELECT F.NM_FUNCIONARIO, F.CD_DEPARTAMENTO, F.CD_BANCO FROM FUNCIONARIOS AS F
WHERE F.CD_BANCO IS NULL


--RETORNA QUANTOS FUNCIONARIOS TEM EM CADA DEPARTAMENTO
SELECT D.NM_DEPARTAMENTO, 
       QTD_FUNC = (SELECT COUNT(*) 
	               FROM FUNCIONARIOS F 
                   WHERE F.CD_DEPARTAMENTO = D.CD_DEPARTAMENTO) 
FROM DEPARTAMENTOS AS D

