CREATE DATABASE FUNCIONARIOS

USE FUNCIONARIOS

CREATE TABLE DEPARTAMENTOS(
CD_DEPARTAMENTO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NM_DEPARTAMENTO VARCHAR(150) NOT NULL
)

CREATE TABLE FUNCIONARIOS(
COD_FUNCIONARIO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOME VARCHAR(150)NOT NULL,
DT_NASCIMENTO DATE,
DT_ADMISSAO DATE,
COD_DEPARTAMENTO INT NOT NULL,
COD_BANCO INT NOT NULL,
FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(CD_DEPARTAMENTO),
FOREIGN KEY (COD_BANCO) REFERENCES BANCOS(CD_BANCO)
)

CREATE TABLE BANCOS(
CD_BANCO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NM_BANCO VARCHAR(150) NOT NULL,
NUM_AGENCIA INT NOT NULL,
NUM_BANCO INT NOT NULL
)

drop database if exists CadEstagiarios


create database FUNCIONARIOS

use FUNCIONARIOS



drop table FUNCIONARIOS

exec sp_columns BANCOS

INSERT INTO BANCOS VALUES
('CAIXA', 1, 4)

SELECT * FROM BANCOS


INSERT INTO FUNCIONARIOS VALUES
('Mateus Borges', '1996-06-16', '2022-04-11', 4, 1),
('Thaisla Camila', '1998-01-10', '2022-04-11', 4, 2),
('Ana Carolina', NULL, '2022-04-11', 4, 3),
('Diego Garcia', NULL, '2022-04-11', 4, 4),
('Diego Tavares', NULL, '2022-04-11', 4, 5),
('Diogo Felismino', NULL, '2022-04-11', 4, 1),
('Miguel dos Santos', NULL, '2022-04-11', 4, 2),
('Kennia Fernandes', NULL, '2022-04-11', 4, 3),
('Anderson Salles', NULL, '2022-04-11', 4, 4),
('Jhonnatan Taveira', NULL, '2022-04-11', 4, 5),
('Vitor Martins', NULL, '2022-04-11', 4, 1)



INSERT INTO DEPARTAMENTOS VALUES
('ESTÁGIO')

UPDATE FUNCIONARIOS
SET DT_NASCIMENTO = 1998-04-07
WHERE NOME = 'Jhonnatan Taveira'

INSERT INTO BANCOS VALUES
('NEON', 1, 1),
('NUBANK', 1, 2),
('C6', 1, 3),
('BRADESCO', 456, 4),
('BRADESCO', 400, 4)

SELECT * FROM FUNCIONARIOS

ALTER TABLE FUNCIONARIOS 
DROP COLUMN SALARIO

ALTER TABLE FUNCIONARIOS
ADD SALARIO DECIMAL(8,2)

UPDATE FUNCIONARIOS 
SET SALARIO = 900.0
WHERE COD_FUNCIONARIO > 6

SP_COLUMNS FUNCIONARIOS

SELECT * FROM FUNCIONARIOS

SELECT IDADE = DATEDIFF(YY, DT_NASCIMENTO, GETDATE()) FROM FUNCIONARIOS WHERE NOME LIKE 'MATEUS%'

SELECT CONVERT(DATE, DT_NASCIMENTO) FROM FUNCIONARIOS WHERE NOME LIKE ''


SELECT IDADE = DATEDIFF(year, (SELECT DT_NASCIMENTO FROM FUNCIONARIOS WHERE NOME LIKE 'MAT%'), CONVERT(date, GETDATE()))

UPDATE FUNCIONARIOS
SET DT_NASCIMENTO = 1996-06-16 00:00:00.000
WHERE NOME LIKE 'MATEUS%'

SELECT F.NOME, F.SALARIO, B.NM_BANCO FROM FUNCIONARIOS AS F
JOIN BANCOS AS B
ON F.COD_BANCO = B.CD_BANCO
WHERE B.NM_BANCO = 'NUBANK'

ALTER TABLE FUNCIONARIOS 
ADD SALARIO DECIMAL(8,2)

UPDATE FUNCIONARIOS
SET SALARIO = 900.0
WHERE COD_FUNCIONARIO = 1

SELECT * FROM FUNCIONARIOS


SELECT COD_FUNCIONARIO, NOME, DT_NASCIMENTO, DATEDIFF(year, DT_NASCIMENTO, CONVERT(date, GETDATE())) AS IDADE FROM FUNCIONARIOS;



USE FUNCIONARIOS

SELECT * FROM BANCOS ORDER BY NM_BANCO DESC

SELECT B.NM_BANCO, F.NM_FUNCIONARIO FROM BANCOS B
JOIN FUNCIONARIOS F
ON B.CD_BANCO = F.CD_BANCO
WHERE F.CD_BANCO IS NULL

SP_COLUMNS FUNCIONARIOS


SELECT * FROM BANCOS
WHERE NU_BANCO LIKE '1%' OR NU_BANCO IS NULL

SELECT * FROM BANCOS

SELECT NM_FUNCIONARIO FROM FUNCIONARIOS
WHERE CONVERT(date, DT_NASCIMENTO) < '2006'



SELECT NM_BANCO FROM BANCOS B 
JOIN FUNCIONARIOS F 
ON B.CD_BANCO = F.CD_BANCO 
WHERE F.CD_BANCO IS NULL

USE FUNCIONARIOS



SELECT NM_BANCO FROM BANCOS B JOIN FUNCIONARIOS F ON B.CD_BANCO = F.CD_BANCO WHERE F.CD_BANCO IS NULL

SELECT B.NM_BANCO FROM BANCOS AS B JOIN FUNCIONARIOS AS F ON B.CD_BANCO = F.CD_BANCO WHERE F.CD_BANCO IS NULL


SELECT * FROM FUNCIONARIOS
SELECT * FROM BANCOS


USE FUNCIONARIOS



SELECT * FROM FUNCIONARIOS
WHERE VL_SALARIO < 200.0 OR YEAR(DT_ADMISSAO) < '1974'

SELECT * FROM FUNCIONARIOS 
WHERE MONTH(DT_ADMISSAO) = 2